name: programmers-be
on:
  push:
    branches:
      - main #main 브랜치에 push 되었을 때

jobs:
  build:
    runs-on: ubuntu-latest #ubuntu 최근 버전에 빌드를 하겠다
    steps:
      - name: Checkout #checkout을 하겠다 CI서버에 갖다놓는 작업을 하라
        uses: actions/checkout@v4

      - name: Set up JDK 17 #해당 우분투에 JDK를 설치하겠습니다. (17버전)
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Grant for gradlew #원래는 스크립트를 작성 해야하지만, 라이브러리가 있음. 설정도 가능!
        run: chmod +x ./gradlew #실행 권한 주기
        shell: bash #bash shell에서

      - name: build gradle #gradle을 실행해라
        run: ./gradlew clean build
        shell: bash

# CI 끝!

